// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CustomTextPosition","status":true,"description":"Customizes the text box position.","parameters":{}},
{"name":"TextPicture","status":false,"description":"Displays text as a picture.","parameters":{}}
];
